lang_name: "English"
title: "Communicable State Machine(CSM) Framework"
ChooseLanguage: "Language"
no_translation: "This page is not available in English yet."
release_note: "Release Notes"
contact_us: "Contact Us"
about: "About"
PageNotFound: "Page not found"
TheRequestedPageCouldNotBeFound: "The requested page could not be found."