lang_name: "English"
title: "Communicable State Machine(CSM)"
ChooseLanguage: "Language"
no_translation: "Sorry, this page is not available in English."
release_note: "Release Notes"
contact_us: "Contact Us"
about: "About"