lang_name: "中文"
title: "可通信状态机框架(CSM)"
ChooseLanguage: "语言"
no_translation: "此页面暂时无中文版"
release_note: "版本更新记录"
contact_us: "联系我们"
about: "关于"
PageNotFound: "页面未找到"
TheRequestedPageCouldNotBeFound: "无法找到所请求的页面."